In [12]:
import pandas as pd
from pathlib import Path

def col_to_index(col: str) -> int:
    """Wandelt Excel-Spaltenbezeichnung (z.B. 'BE', 'ZY') in 0-basierten Index um."""
    col = col.upper()
    result = 0
    for c in col:
        result = result * 26 + (ord(c) - ord('A') + 1)
    return result - 1

# Spaltenranges definieren
RANGES = {
    "Ergebnisse der Fragebögen": ("BE", "BM"),
    "Aktuelle Prophylaxe-Medikamente": ("ZY", "AKY"),
}

for csv_file in Path("patienten-visiten").glob("*.csv"):
    print(f"\n{'='*60}")
    print(f"Datei: {csv_file.name}")
    print('='*60)

    df = pd.read_csv(csv_file, nrows=0, sep=";")  # nur Header laden
    headers = list(df.columns)

    for bereich, (start_col, end_col) in RANGES.items():
        start_idx = col_to_index(start_col)
        end_idx = col_to_index(end_col)

        # Nur Spalten nehmen, die im DataFrame vorhanden sind
        cols_in_range = headers[start_idx : end_idx + 1]

        print(f"\n📋 {bereich} (Spalten {start_col}–{end_col}):")
        if cols_in_range:
            for i, col in enumerate(cols_in_range, start=start_idx + 1):
                # Spaltennummer als Excel-Buchstabe berechnen
                excel_col = ""
                n = i
                while n > 0:
                    n, rem = divmod(n - 1, 26)
                    excel_col = chr(65 + rem) + excel_col
                print(f"  {excel_col:>4}: {col}")
        else:
            print("  (keine Spalten in diesem Bereich gefunden)")

============================================================
Datei: Patients_V10_02-03-2026.csv
============================================================

📋 Ergebnisse der Fragebögen (Spalten BE–BM):
    BE: dass_depression_K10
    BF: dass_fear_K10
    BG: dass_stress_K10
    BH: midas_result_K10
    BI: vr12_msc_K10
    BJ: vr12_psc_K10
    BK: gvas_result_K10
    BL: pgic_result_K10
    BM: chiq_result_K10

📋 Aktuelle Prophylaxe-Medikamente (Spalten ZY–AKY):
    ZY: number_prophy_K10
    ZZ: preventive_name_p1_K10
   AAA: dosage_p1_K10
   AAB: dosage_other_p1_K10
   AAC: dosage_unknown_p1_K10
   AAD: count_p1_K10
   AAE: intake_schema_morning_p1_K10
   AAF: intake_schema_noon_p1_K10
   AAG: intake_schema_evening_p1_K10
   AAH: intake_schema_second_day_p1_K10
   AAI: intake_schema_other_p1_K10
   AAJ: intake_schema_unknown_p1_K10
   AAK: special_intake_schema_id_p1_K10
   AAL: begin_p1_K10
   AAM: effect_p1_K10
   AAN: tolerability_p1_K10
   AAO: satisfaction_p1_K10
   AAP: adherence_p1_K10
   AAQ: number_adverse_p1_K10
   AAR: gase_sum_all_p1_K10
   AAS: gase_sum_off_p1_K10
   AAT: adverse1_p1_K10
   AAU: gase1_p1_K10
   AAV: adverse2_p1_K10
   AAW: gase2_p1_K10
   AAX: adverse3_p1_K10
   AAY: gase3_p1_K10
   AAZ: preventive_name_p2_K10
   ABA: dosage_p2_K10
   ABB: dosage_other_p2_K10
   ABC: dosage_unknown_p2_K10
   ABD: count_p2_K10
   ABE: intake_schema_morning_p2_K10
   ABF: intake_schema_noon_p2_K10
   ABG: intake_schema_evening_p2_K10
   ABH: intake_schema_second_day_p2_K10
   ABI: intake_schema_other_p2_K10
   ABJ: intake_schema_unknown_p2_K10
   ABK: special_intake_schema_id_p2_K10
   ABL: begin_p2_K10
   ABM: effect_p2_K10
   ABN: tolerability_p2_K10
   ABO: satisfaction_p2_K10
   ABP: adherence_p2_K10
   ABQ: number_adverse_p2_K10
   ABR: gase_sum_all_p2_K10
   ABS: gase_sum_off_p2_K10
   ABT: adverse1_p2_K10
   ABU: gase1_p2_K10
   ABV: adverse2_p2_K10
   ABW: gase2_p2_K10
   ABX: adverse3_p2_K10
   ABY: gase3_p2_K10
   ABZ: preventive_name_p3_K10
   ACA: dosage_p3_K10
   ACB: dosage_other_p3_K10
   ACC: dosage_unknown_p3_K10
   ACD: count_p3_K10
   ACE: intake_schema_morning_p3_K10
   ACF: intake_schema_noon_p3_K10
   ACG: intake_schema_evening_p3_K10
   ACH: intake_schema_second_day_p3_K10
   ACI: intake_schema_other_p3_K10
   ACJ: intake_schema_unknown_p3_K10
   ACK: special_intake_schema_id_p3_K10
   ACL: begin_p3_K10
   ACM: effect_p3_K10
   ACN: tolerability_p3_K10
   ACO: satisfaction_p3_K10
   ACP: adherence_p3_K10
   ACQ: number_adverse_p3_K10
   ACR: gase_sum_all_p3_K10
   ACS: gase_sum_off_p3_K10
   ACT: adverse1_p3_K10
   ACU: gase1_p3_K10
   ACV: adverse2_p3_K10
   ACW: gase2_p3_K10
   ACX: adverse3_p3_K10
   ACY: gase3_p3_K10
   ACZ: preventive_name_p4_K10
   ADA: dosage_p4_K10
   ADB: dosage_other_p4_K10
   ADC: dosage_unknown_p4_K10
   ADD: count_p4_K10
   ADE: intake_schema_morning_p4_K10
   ADF: intake_schema_noon_p4_K10
   ADG: intake_schema_evening_p4_K10
   ADH: intake_schema_second_day_p4_K10
   ADI: intake_schema_other_p4_K10
   ADJ: intake_schema_unknown_p4_K10
   ADK: special_intake_schema_id_p4_K10
   ADL: begin_p4_K10
   ADM: effect_p4_K10
   ADN: tolerability_p4_K10
   ADO: satisfaction_p4_K10
   ADP: adherence_p4_K10
   ADQ: number_adverse_p4_K10
   ADR: gase_sum_all_p4_K10
   ADS: gase_sum_off_p4_K10
   ADT: adverse1_p4_K10
   ADU: gase1_p4_K10
   ADV: adverse2_p4_K10
   ADW: gase2_p4_K10
   ADX: adverse3_p4_K10
   ADY: gase3_p4_K10
   ADZ: preventive_name_p5_K10
   AEA: dosage_p5_K10
   AEB: dosage_other_p5_K10
   AEC: dosage_unknown_p5_K10
   AED: count_p5_K10
   AEE: intake_schema_morning_p5_K10
   AEF: intake_schema_noon_p5_K10
   AEG: intake_schema_evening_p5_K10
   AEH: intake_schema_second_day_p5_K10
   AEI: intake_schema_other_p5_K10
   AEJ: intake_schema_unknown_p5_K10
   AEK: special_intake_schema_id_p5_K10
   AEL: begin_p5_K10
   AEM: effect_p5_K10
   AEN: tolerability_p5_K10
   AEO: satisfaction_p5_K10
   AEP: adherence_p5_K10
   AEQ: number_adverse_p5_K10
   AER: gase_sum_all_p5_K10
   AES: gase_sum_off_p5_K10
   AET: adverse1_p5_K10
   AEU: gase1_p5_K10
   AEV: adverse2_p5_K10
   AEW: gase2_p5_K10
   AEX: adverse3_p5_K10
   AEY: gase3_p5_K10
   AEZ: preventive_name_p6_K10
   AFA: dosage_p6_K10
   AFB: dosage_other_p6_K10
   AFC: dosage_unknown_p6_K10
   AFD: count_p6_K10
   AFE: intake_schema_morning_p6_K10
   AFF: intake_schema_noon_p6_K10
   AFG: intake_schema_evening_p6_K10
   AFH: intake_schema_second_day_p6_K10
   AFI: intake_schema_other_p6_K10
   AFJ: intake_schema_unknown_p6_K10
   AFK: special_intake_schema_id_p6_K10
   AFL: begin_p6_K10
   AFM: effect_p6_K10
   AFN: tolerability_p6_K10
   AFO: satisfaction_p6_K10
   AFP: adherence_p6_K10
   AFQ: number_adverse_p6_K10
   AFR: gase_sum_all_p6_K10
   AFS: gase_sum_off_p6_K10
   AFT: adverse1_p6_K10
   AFU: gase1_p6_K10
   AFV: adverse2_p6_K10
   AFW: gase2_p6_K10
   AFX: adverse3_p6_K10
   AFY: gase3_p6_K10
   AFZ: preventive_name_p7_K10
   AGA: dosage_p7_K10
   AGB: dosage_other_p7_K10
   AGC: dosage_unknown_p7_K10
   AGD: count_p7_K10
   AGE: intake_schema_morning_p7_K10
   AGF: intake_schema_noon_p7_K10
   AGG: intake_schema_evening_p7_K10
   AGH: intake_schema_second_day_p7_K10
   AGI: intake_schema_other_p7_K10
   AGJ: intake_schema_unknown_p7_K10
   AGK: special_intake_schema_id_p7_K10
   AGL: begin_p7_K10
   AGM: effect_p7_K10
   AGN: tolerability_p7_K10
   AGO: satisfaction_p7_K10
   AGP: adherence_p7_K10
   AGQ: number_adverse_p7_K10
   AGR: gase_sum_all_p7_K10
   AGS: gase_sum_off_p7_K10
   AGT: adverse1_p7_K10
   AGU: gase1_p7_K10
   AGV: adverse2_p7_K10
   AGW: gase2_p7_K10
   AGX: adverse3_p7_K10
   AGY: gase3_p7_K10
   AGZ: preventive_name_p8_K10
   AHA: dosage_p8_K10
   AHB: dosage_other_p8_K10
   AHC: dosage_unknown_p8_K10
   AHD: count_p8_K10
   AHE: intake_schema_morning_p8_K10
   AHF: intake_schema_noon_p8_K10
   AHG: intake_schema_evening_p8_K10
   AHH: intake_schema_second_day_p8_K10
   AHI: intake_schema_other_p8_K10
   AHJ: intake_schema_unknown_p8_K10
   AHK: special_intake_schema_id_p8_K10
   AHL: begin_p8_K10
   AHM: effect_p8_K10
   AHN: tolerability_p8_K10
   AHO: satisfaction_p8_K10
   AHP: adherence_p8_K10
   AHQ: number_adverse_p8_K10
   AHR: gase_sum_all_p8_K10
   AHS: gase_sum_off_p8_K10
   AHT: adverse1_p8_K10
   AHU: gase1_p8_K10
   AHV: adverse2_p8_K10
   AHW: gase2_p8_K10
   AHX: adverse3_p8_K10
   AHY: gase3_p8_K10
   AHZ: preventive_name_p9_K10
   AIA: dosage_p9_K10
   AIB: dosage_other_p9_K10
   AIC: dosage_unknown_p9_K10
   AID: count_p9_K10
   AIE: intake_schema_morning_p9_K10
   AIF: intake_schema_noon_p9_K10
   AIG: intake_schema_evening_p9_K10
   AIH: intake_schema_second_day_p9_K10
   AII: intake_schema_other_p9_K10
   AIJ: intake_schema_unknown_p9_K10
   AIK: special_intake_schema_id_p9_K10
   AIL: begin_p9_K10
   AIM: effect_p9_K10
   AIN: tolerability_p9_K10
   AIO: satisfaction_p9_K10
   AIP: adherence_p9_K10
   AIQ: number_adverse_p9_K10
   AIR: gase_sum_all_p9_K10
   AIS: gase_sum_off_p9_K10
   AIT: adverse1_p9_K10
   AIU: gase1_p9_K10
   AIV: adverse2_p9_K10
   AIW: gase2_p9_K10
   AIX: adverse3_p9_K10
   AIY: gase3_p9_K10
   AIZ: preventive_name_p10_K10
   AJA: dosage_p10_K10
   AJB: dosage_other_p10_K10
   AJC: dosage_unknown_p10_K10
   AJD: count_p10_K10
   AJE: intake_schema_morning_p10_K10
   AJF: intake_schema_noon_p10_K10
   AJG: intake_schema_evening_p10_K10
   AJH: intake_schema_second_day_p10_K10
   AJI: intake_schema_other_p10_K10
   AJJ: intake_schema_unknown_p10_K10
   AJK: special_intake_schema_id_p10_K10
   AJL: begin_p10_K10
   AJM: effect_p10_K10
   AJN: tolerability_p10_K10
   AJO: satisfaction_p10_K10
   AJP: adherence_p10_K10
   AJQ: number_adverse_p10_K10
   AJR: gase_sum_all_p10_K10
   AJS: gase_sum_off_p10_K10
   AJT: adverse1_p10_K10
   AJU: gase1_p10_K10
   AJV: adverse2_p10_K10
   AJW: gase2_p10_K10
   AJX: adverse3_p10_K10
   AJY: gase3_p10_K10
   AJZ: preventive_name_p11_K10
   AKA: dosage_p11_K10
   AKB: dosage_other_p11_K10
   AKC: dosage_unknown_p11_K10
   AKD: count_p11_K10
   AKE: intake_schema_morning_p11_K10
   AKF: intake_schema_noon_p11_K10
   AKG: intake_schema_evening_p11_K10
   AKH: intake_schema_second_day_p11_K10
   AKI: intake_schema_other_p11_K10
   AKJ: intake_schema_unknown_p11_K10
   AKK: special_intake_schema_id_p11_K10
   AKL: begin_p11_K10
   AKM: effect_p11_K10
   AKN: tolerability_p11_K10
   AKO: satisfaction_p11_K10
   AKP: adherence_p11_K10
   AKQ: number_adverse_p11_K10
   AKR: gase_sum_all_p11_K10
   AKS: gase_sum_off_p11_K10
   AKT: adverse1_p11_K10
   AKU: gase1_p11_K10
   AKV: adverse2_p11_K10
   AKW: gase2_p11_K10
   AKX: adverse3_p11_K10
   AKY: gase3_p11_K10

============================================================
Datei: Patients_V11_02-03-2026.csv
============================================================

📋 Ergebnisse der Fragebögen (Spalten BE–BM):
    BE: dass_depression_K11
    BF: dass_fear_K11
    BG: dass_stress_K11
    BH: midas_result_K11
    BI: vr12_msc_K11
    BJ: vr12_psc_K11
    BK: gvas_result_K11
    BL: pgic_result_K11
    BM: chiq_result_K11

📋 Aktuelle Prophylaxe-Medikamente (Spalten ZY–AKY):
    ZY: number_prophy_K11
    ZZ: preventive_name_p1_K11
   AAA: dosage_p1_K11
   AAB: dosage_other_p1_K11
   AAC: dosage_unknown_p1_K11
   AAD: count_p1_K11
   AAE: intake_schema_morning_p1_K11
   AAF: intake_schema_noon_p1_K11
   AAG: intake_schema_evening_p1_K11
   AAH: intake_schema_second_day_p1_K11
   AAI: intake_schema_other_p1_K11
   AAJ: intake_schema_unknown_p1_K11
   AAK: special_intake_schema_id_p1_K11
   AAL: begin_p1_K11
   AAM: effect_p1_K11
   AAN: tolerability_p1_K11
   AAO: satisfaction_p1_K11
   AAP: adherence_p1_K11
   AAQ: number_adverse_p1_K11
   AAR: gase_sum_all_p1_K11
   AAS: gase_sum_off_p1_K11
   AAT: adverse1_p1_K11
   AAU: gase1_p1_K11
   AAV: adverse2_p1_K11
   AAW: gase2_p1_K11
   AAX: adverse3_p1_K11
   AAY: gase3_p1_K11
   AAZ: preventive_name_p2_K11
   ABA: dosage_p2_K11
   ABB: dosage_other_p2_K11
   ABC: dosage_unknown_p2_K11
   ABD: count_p2_K11
   ABE: intake_schema_morning_p2_K11
   ABF: intake_schema_noon_p2_K11
   ABG: intake_schema_evening_p2_K11
   ABH: intake_schema_second_day_p2_K11
   ABI: intake_schema_other_p2_K11
   ABJ: intake_schema_unknown_p2_K11
   ABK: special_intake_schema_id_p2_K11
   ABL: begin_p2_K11
   ABM: effect_p2_K11
   ABN: tolerability_p2_K11
   ABO: satisfaction_p2_K11
   ABP: adherence_p2_K11
   ABQ: number_adverse_p2_K11
   ABR: gase_sum_all_p2_K11
   ABS: gase_sum_off_p2_K11
   ABT: adverse1_p2_K11
   ABU: gase1_p2_K11
   ABV: adverse2_p2_K11
   ABW: gase2_p2_K11
   ABX: adverse3_p2_K11
   ABY: gase3_p2_K11
   ABZ: preventive_name_p3_K11
   ACA: dosage_p3_K11
   ACB: dosage_other_p3_K11
   ACC: dosage_unknown_p3_K11
   ACD: count_p3_K11
   ACE: intake_schema_morning_p3_K11
   ACF: intake_schema_noon_p3_K11
   ACG: intake_schema_evening_p3_K11
   ACH: intake_schema_second_day_p3_K11
   ACI: intake_schema_other_p3_K11
   ACJ: intake_schema_unknown_p3_K11
   ACK: special_intake_schema_id_p3_K11
   ACL: begin_p3_K11
   ACM: effect_p3_K11
   ACN: tolerability_p3_K11
   ACO: satisfaction_p3_K11
   ACP: adherence_p3_K11
   ACQ: number_adverse_p3_K11
   ACR: gase_sum_all_p3_K11
   ACS: gase_sum_off_p3_K11
   ACT: adverse1_p3_K11
   ACU: gase1_p3_K11
   ACV: adverse2_p3_K11
   ACW: gase2_p3_K11
   ACX: adverse3_p3_K11
   ACY: gase3_p3_K11
   ACZ: preventive_name_p4_K11
   ADA: dosage_p4_K11
   ADB: dosage_other_p4_K11
   ADC: dosage_unknown_p4_K11
   ADD: count_p4_K11
   ADE: intake_schema_morning_p4_K11
   ADF: intake_schema_noon_p4_K11
   ADG: intake_schema_evening_p4_K11
   ADH: intake_schema_second_day_p4_K11
   ADI: intake_schema_other_p4_K11
   ADJ: intake_schema_unknown_p4_K11
   ADK: special_intake_schema_id_p4_K11
   ADL: begin_p4_K11
   ADM: effect_p4_K11
   ADN: tolerability_p4_K11
   ADO: satisfaction_p4_K11
   ADP: adherence_p4_K11
   ADQ: number_adverse_p4_K11
   ADR: gase_sum_all_p4_K11
   ADS: gase_sum_off_p4_K11
   ADT: adverse1_p4_K11
   ADU: gase1_p4_K11
   ADV: adverse2_p4_K11
   ADW: gase2_p4_K11
   ADX: adverse3_p4_K11
   ADY: gase3_p4_K11
   ADZ: preventive_name_p5_K11
   AEA: dosage_p5_K11
   AEB: dosage_other_p5_K11
   AEC: dosage_unknown_p5_K11
   AED: count_p5_K11
   AEE: intake_schema_morning_p5_K11
   AEF: intake_schema_noon_p5_K11
   AEG: intake_schema_evening_p5_K11
   AEH: intake_schema_second_day_p5_K11
   AEI: intake_schema_other_p5_K11
   AEJ: intake_schema_unknown_p5_K11
   AEK: special_intake_schema_id_p5_K11
   AEL: begin_p5_K11
   AEM: effect_p5_K11
   AEN: tolerability_p5_K11
   AEO: satisfaction_p5_K11
   AEP: adherence_p5_K11
   AEQ: number_adverse_p5_K11
   AER: gase_sum_all_p5_K11
   AES: gase_sum_off_p5_K11
   AET: adverse1_p5_K11
   AEU: gase1_p5_K11
   AEV: adverse2_p5_K11
   AEW: gase2_p5_K11
   AEX: adverse3_p5_K11
   AEY: gase3_p5_K11
   AEZ: preventive_name_p6_K11
   AFA: dosage_p6_K11
   AFB: dosage_other_p6_K11
   AFC: dosage_unknown_p6_K11
   AFD: count_p6_K11
   AFE: intake_schema_morning_p6_K11
   AFF: intake_schema_noon_p6_K11
   AFG: intake_schema_evening_p6_K11
   AFH: intake_schema_second_day_p6_K11
   AFI: intake_schema_other_p6_K11
   AFJ: intake_schema_unknown_p6_K11
   AFK: special_intake_schema_id_p6_K11
   AFL: begin_p6_K11
   AFM: effect_p6_K11
   AFN: tolerability_p6_K11
   AFO: satisfaction_p6_K11
   AFP: adherence_p6_K11
   AFQ: number_adverse_p6_K11
   AFR: gase_sum_all_p6_K11
   AFS: gase_sum_off_p6_K11
   AFT: adverse1_p6_K11
   AFU: gase1_p6_K11
   AFV: adverse2_p6_K11
   AFW: gase2_p6_K11
   AFX: adverse3_p6_K11
   AFY: gase3_p6_K11
   AFZ: preventive_name_p7_K11
   AGA: dosage_p7_K11
   AGB: dosage_other_p7_K11
   AGC: dosage_unknown_p7_K11
   AGD: count_p7_K11
   AGE: intake_schema_morning_p7_K11
   AGF: intake_schema_noon_p7_K11
   AGG: intake_schema_evening_p7_K11
   AGH: intake_schema_second_day_p7_K11
   AGI: intake_schema_other_p7_K11
   AGJ: intake_schema_unknown_p7_K11
   AGK: special_intake_schema_id_p7_K11
   AGL: begin_p7_K11
   AGM: effect_p7_K11
   AGN: tolerability_p7_K11
   AGO: satisfaction_p7_K11
   AGP: adherence_p7_K11
   AGQ: number_adverse_p7_K11
   AGR: gase_sum_all_p7_K11
   AGS: gase_sum_off_p7_K11
   AGT: adverse1_p7_K11
   AGU: gase1_p7_K11
   AGV: adverse2_p7_K11
   AGW: gase2_p7_K11
   AGX: adverse3_p7_K11
   AGY: gase3_p7_K11
   AGZ: preventive_name_p8_K11
   AHA: dosage_p8_K11
   AHB: dosage_other_p8_K11
   AHC: dosage_unknown_p8_K11
   AHD: count_p8_K11
   AHE: intake_schema_morning_p8_K11
   AHF: intake_schema_noon_p8_K11
   AHG: intake_schema_evening_p8_K11
   AHH: intake_schema_second_day_p8_K11
   AHI: intake_schema_other_p8_K11
   AHJ: intake_schema_unknown_p8_K11
   AHK: special_intake_schema_id_p8_K11
   AHL: begin_p8_K11
   AHM: effect_p8_K11
   AHN: tolerability_p8_K11
   AHO: satisfaction_p8_K11
   AHP: adherence_p8_K11
   AHQ: number_adverse_p8_K11
   AHR: gase_sum_all_p8_K11
   AHS: gase_sum_off_p8_K11
   AHT: adverse1_p8_K11
   AHU: gase1_p8_K11
   AHV: adverse2_p8_K11
   AHW: gase2_p8_K11
   AHX: adverse3_p8_K11
   AHY: gase3_p8_K11
   AHZ: preventive_name_p9_K11
   AIA: dosage_p9_K11
   AIB: dosage_other_p9_K11
   AIC: dosage_unknown_p9_K11
   AID: count_p9_K11
   AIE: intake_schema_morning_p9_K11
   AIF: intake_schema_noon_p9_K11
   AIG: intake_schema_evening_p9_K11
   AIH: intake_schema_second_day_p9_K11
   AII: intake_schema_other_p9_K11
   AIJ: intake_schema_unknown_p9_K11
   AIK: special_intake_schema_id_p9_K11
   AIL: begin_p9_K11
   AIM: effect_p9_K11
   AIN: tolerability_p9_K11
   AIO: satisfaction_p9_K11
   AIP: adherence_p9_K11
   AIQ: number_adverse_p9_K11
   AIR: gase_sum_all_p9_K11
   AIS: gase_sum_off_p9_K11
   AIT: adverse1_p9_K11
   AIU: gase1_p9_K11
   AIV: adverse2_p9_K11
   AIW: gase2_p9_K11
   AIX: adverse3_p9_K11
   AIY: gase3_p9_K11
   AIZ: preventive_name_p10_K11
   AJA: dosage_p10_K11
   AJB: dosage_other_p10_K11
   AJC: dosage_unknown_p10_K11
   AJD: count_p10_K11
   AJE: intake_schema_morning_p10_K11
   AJF: intake_schema_noon_p10_K11
   AJG: intake_schema_evening_p10_K11
   AJH: intake_schema_second_day_p10_K11
   AJI: intake_schema_other_p10_K11
   AJJ: intake_schema_unknown_p10_K11
   AJK: special_intake_schema_id_p10_K11
   AJL: begin_p10_K11
   AJM: effect_p10_K11
   AJN: tolerability_p10_K11
   AJO: satisfaction_p10_K11
   AJP: adherence_p10_K11
   AJQ: number_adverse_p10_K11
   AJR: gase_sum_all_p10_K11
   AJS: gase_sum_off_p10_K11
   AJT: adverse1_p10_K11
   AJU: gase1_p10_K11
   AJV: adverse2_p10_K11
   AJW: gase2_p10_K11
   AJX: adverse3_p10_K11
   AJY: gase3_p10_K11
   AJZ: preventive_name_p11_K11
   AKA: dosage_p11_K11
   AKB: dosage_other_p11_K11
   AKC: dosage_unknown_p11_K11
   AKD: count_p11_K11
   AKE: intake_schema_morning_p11_K11
   AKF: intake_schema_noon_p11_K11
   AKG: intake_schema_evening_p11_K11
   AKH: intake_schema_second_day_p11_K11
   AKI: intake_schema_other_p11_K11
   AKJ: intake_schema_unknown_p11_K11
   AKK: special_intake_schema_id_p11_K11
   AKL: begin_p11_K11
   AKM: effect_p11_K11
   AKN: tolerability_p11_K11
   AKO: satisfaction_p11_K11
   AKP: adherence_p11_K11
   AKQ: number_adverse_p11_K11
   AKR: gase_sum_all_p11_K11
   AKS: gase_sum_off_p11_K11
   AKT: adverse1_p11_K11
   AKU: gase1_p11_K11
   AKV: adverse2_p11_K11
   AKW: gase2_p11_K11
   AKX: adverse3_p11_K11
   AKY: gase3_p11_K11

============================================================
Datei: Patients_V12_02-03-2026.csv
============================================================

📋 Ergebnisse der Fragebögen (Spalten BE–BM):
    BE: dass_depression_K12
    BF: dass_fear_K12
    BG: dass_stress_K12
    BH: midas_result_K12
    BI: vr12_msc_K12
    BJ: vr12_psc_K12
    BK: gvas_result_K12
    BL: pgic_result_K12
    BM: chiq_result_K12

📋 Aktuelle Prophylaxe-Medikamente (Spalten ZY–AKY):
    ZY: number_prophy_K12
    ZZ: preventive_name_p1_K12
   AAA: dosage_p1_K12
   AAB: dosage_other_p1_K12
   AAC: dosage_unknown_p1_K12
   AAD: count_p1_K12
   AAE: intake_schema_morning_p1_K12
   AAF: intake_schema_noon_p1_K12
   AAG: intake_schema_evening_p1_K12
   AAH: intake_schema_second_day_p1_K12
   AAI: intake_schema_other_p1_K12
   AAJ: intake_schema_unknown_p1_K12
   AAK: special_intake_schema_id_p1_K12
   AAL: begin_p1_K12
   AAM: effect_p1_K12
   AAN: tolerability_p1_K12
   AAO: satisfaction_p1_K12
   AAP: adherence_p1_K12
   AAQ: number_adverse_p1_K12
   AAR: gase_sum_all_p1_K12
   AAS: gase_sum_off_p1_K12
   AAT: adverse1_p1_K12
   AAU: gase1_p1_K12
   AAV: adverse2_p1_K12
   AAW: gase2_p1_K12
   AAX: adverse3_p1_K12
   AAY: gase3_p1_K12
   AAZ: preventive_name_p2_K12
   ABA: dosage_p2_K12
   ABB: dosage_other_p2_K12
   ABC: dosage_unknown_p2_K12
   ABD: count_p2_K12
   ABE: intake_schema_morning_p2_K12
   ABF: intake_schema_noon_p2_K12
   ABG: intake_schema_evening_p2_K12
   ABH: intake_schema_second_day_p2_K12
   ABI: intake_schema_other_p2_K12
   ABJ: intake_schema_unknown_p2_K12
   ABK: special_intake_schema_id_p2_K12
   ABL: begin_p2_K12
   ABM: effect_p2_K12
   ABN: tolerability_p2_K12
   ABO: satisfaction_p2_K12
   ABP: adherence_p2_K12
   ABQ: number_adverse_p2_K12
   ABR: gase_sum_all_p2_K12
   ABS: gase_sum_off_p2_K12
   ABT: adverse1_p2_K12
   ABU: gase1_p2_K12
   ABV: adverse2_p2_K12
   ABW: gase2_p2_K12
   ABX: adverse3_p2_K12
   ABY: gase3_p2_K12
   ABZ: preventive_name_p3_K12
   ACA: dosage_p3_K12
   ACB: dosage_other_p3_K12
   ACC: dosage_unknown_p3_K12
   ACD: count_p3_K12
   ACE: intake_schema_morning_p3_K12
   ACF: intake_schema_noon_p3_K12
   ACG: intake_schema_evening_p3_K12
   ACH: intake_schema_second_day_p3_K12
   ACI: intake_schema_other_p3_K12
   ACJ: intake_schema_unknown_p3_K12
   ACK: special_intake_schema_id_p3_K12
   ACL: begin_p3_K12
   ACM: effect_p3_K12
   ACN: tolerability_p3_K12
   ACO: satisfaction_p3_K12
   ACP: adherence_p3_K12
   ACQ: number_adverse_p3_K12
   ACR: gase_sum_all_p3_K12
   ACS: gase_sum_off_p3_K12
   ACT: adverse1_p3_K12
   ACU: gase1_p3_K12
   ACV: adverse2_p3_K12
   ACW: gase2_p3_K12
   ACX: adverse3_p3_K12

In [14]:
import pandas as pd
from pathlib import Path

files = sorted(Path("./patienten-visiten").glob("Patients_V*_02-03-2026.csv"))
len(files), files[:3]

(24,
 [WindowsPath('patienten-visiten/Patients_V10_02-03-2026.csv'),
  WindowsPath('patienten-visiten/Patients_V11_02-03-2026.csv'),
  WindowsPath('patienten-visiten/Patients_V12_02-03-2026.csv')])

In [26]:
def extract_questionnaire_cols(columns):
    keys = [
        "id_patient",
        "dass_depression",
        "dass_fear",
        "dass_stress",
        "midas_result",
        "vr12_msc",
        "vr12_psc",
        "gvas_result",
        "pgic_result",
        "chiq_result"
    ]
    return [c for c in columns if any(k in c for k in keys)]

In [27]:
def extract_prophylaxe_cols(columns):
    keys = [
        "id_patient",
        "number_prophy",
        "preventive_name",
        "dosage",
        "intake_schema",
        "special_intake_schema",
        "begin",
        "effect",
        "tolerability",
        "satisfaction",
        "adherence",
        "number_adverse",
        "gase_",
        "adverse"
    ]
    return [c for c in columns if any(k in c for k in keys)]

In [28]:
def process_file(file_path):
    df = pd.read_csv(
        file_path,
        engine="python",        # robuster Parser
        sep=";"
    )

    cols = df.columns

    questionnaire_cols = extract_questionnaire_cols(cols)
    prophylaxe_cols = extract_prophylaxe_cols(cols)

    questionnaire_df = df[questionnaire_cols].copy()
    prophylaxe_df = df[prophylaxe_cols].copy()

    return questionnaire_df, prophylaxe_df

In [37]:
questionnaire_all = {}
prophylaxe_all = {}

for f in files:
    q_df, p_df = process_file(f)

    key = f.stem
    questionnaire_all[key] = q_df
    prophylaxe_all[key] = p_df

len(questionnaire_all), len(prophylaxe_all)

(24, 24)

In [42]:
def filter_prophylaxe_df(df):
    keep_keys = [
        "id_patient",
        "preventive_name",
    ]

    cols = df.columns
    selected = [c for c in cols if any(k in c for k in keep_keys)]

    return df[selected].copy()

In [45]:
prophylaxe_filtered = {}

for k, df in prophylaxe_all.items():
    prophylaxe_filtered[k] = filter_prophylaxe_df(df)

len(prophylaxe_filtered)

24

In [48]:
def extract_med_list(df):
    med_cols = [c for c in df.columns if "preventive_name" in c]

    meds = df[med_cols].values.flatten()

    meds = [
        m for m in meds
        if pd.notna(m)
        and str(m).strip() != ""
        and str(m).strip() != "0"
    ]

    return set(meds)

In [49]:
med_history = {}

for file_name, df in prophylaxe_all.items():

    # Patient ID Spalte (falls vorhanden)
    if "id_patient" not in df.columns:
        continue

    for pid, subdf in df.groupby("id_patient"):

        meds = extract_med_list(subdf)

        med_history.setdefault(pid, {})[file_name] = meds

In [52]:
import re

def get_visit_number(name):
    match = re.search(r"V(\d+)", name)
    return int(match.group(1)) if match else float("inf")

In [106]:
med_events = []

for pid, timeline in med_history.items():

    visits = sorted(timeline.keys(), key=get_visit_number)

    for i in range(1, len(visits)):

        prev_visit = visits[i - 1]
        curr_visit = visits[i]

        prev_meds = timeline[prev_visit]
        curr_meds = timeline[curr_visit]

        started = curr_meds - prev_meds
        stopped = prev_meds - curr_meds

        # ❗ nur echte Änderungen
        if not started and not stopped:
            continue

        # 🔥 CHANGE = Übergang endet in curr_visit
        change_visit = curr_visit

        # 🔥 EFFECT START = DIREKT curr_visit
        effect_from = curr_visit

        # optional: next observation window
        effect_to = visits[i + 1] if i + 1 < len(visits) else None

        med_events.append({
            "patient": pid,

            # change window
            "change_from": prev_visit,
            "change_to": curr_visit,

            # 🔥 corrected effect mapping
            "effect_from": effect_from,
            "effect_to": effect_to,

            "started": list(started),
            "stopped": list(stopped),

            "event_visit": change_visit
        })

In [107]:
med_events_df = pd.DataFrame(med_events)
med_events_df.head()

,patient,change_from,change_to,effect_from,effect_to,started,stopped,event_visit
0,10614987,Patients_V1_02-03-2026,Patients_V3_02-03-2026,Patients_V3_02-03-2026,Patients_V4_02-03-2026,[Magnesium],[],Patients_V3_02-03-2026
1,10614987,Patients_V7_02-03-2026,Patients_V9_02-03-2026,Patients_V9_02-03-2026,Patients_V10_02-03-2026,[Metoprolol],[],Patients_V9_02-03-2026
2,10614987,Patients_V10_02-03-2026,Patients_V11_02-03-2026,Patients_V11_02-03-2026,Patients_Vlast_02-03-2026,[Venlafaxin],[],Patients_V11_02-03-2026
3,10740020,Patients_V1_02-03-2026,Patients_V2_02-03-2026,Patients_V2_02-03-2026,Patients_V3_02-03-2026,[Galcanezumab],[],Patients_V2_02-03-2026
4,10740020,Patients_V4_02-03-2026,Patients_V5_02-03-2026,Patients_V5_02-03-2026,Patients_V6_02-03-2026,[Eptinezumab],[],Patients_V5_02-03-2026

In [88]:
questionnaire_by_visit = {}

for visit_name, df in questionnaire_all.items():
    if "id_patient" not in df.columns:
        continue

    questionnaire_by_visit[visit_name] = df.set_index("id_patient")

In [89]:
def compute_outcome_delta(pid, v_from, v_to):
    fb_from = questionnaire_by_visit[v_from].loc[pid]
    fb_to = questionnaire_by_visit[v_to].loc[pid]

    # nur numerische Spalten
    diff = fb_to - fb_from

    return diff

In [90]:
import pandas as pd

def get_value(df, pid, key_part):
    cols = [c for c in df.columns if key_part in c]
    if not cols:
        return None

    val = df.loc[pid, cols[0]]

    if pd.isna(val):
        return None

    # 🔥 Komma → Punkt
    if isinstance(val, str):
        val = val.replace(",", ".")

    val = pd.to_numeric(val, errors="coerce")

    if pd.isna(val):
        return None

    return float(val)

In [91]:
def safe_delta(fb_from, fb_to, pid, key):
    a = get_value(fb_from, pid, key)
    b = get_value(fb_to, pid, key)

    if a is None or b is None:
        return None

    return b - a

In [108]:
enriched_events = []

for row in med_events_df.to_dict("records"):

    pid = row["patient"]
    v_from = row["effect_from"]
    v_to = row["effect_to"]

    if v_from not in questionnaire_by_visit or v_to not in questionnaire_by_visit:
        continue

    fb_from = questionnaire_by_visit[v_from]
    fb_to = questionnaire_by_visit[v_to]

    if pid not in fb_from.index or pid not in fb_to.index:
        continue

    enriched_events.append({
        **row,

        "dass_depression_delta": safe_delta(fb_from, fb_to, pid, "dass_depression"),
        "dass_fear_delta": safe_delta(fb_from, fb_to, pid, "dass_fear"),
        "dass_stress_delta": safe_delta(fb_from, fb_to, pid, "dass_stress"),

        "midas_delta": safe_delta(fb_from, fb_to, pid, "midas_result"),
        "vr12_msc_delta": safe_delta(fb_from, fb_to, pid, "vr12_msc"),
        "vr12_psc_delta": safe_delta(fb_from, fb_to, pid, "vr12_psc"),

        "gvas_delta": safe_delta(fb_from, fb_to, pid, "gvas_result"),
        "pgic_delta": safe_delta(fb_from, fb_to, pid, "pgic_result"),
        "chiq_delta": safe_delta(fb_from, fb_to, pid, "chiq_result"),
    })

In [109]:
med_outcome_df = pd.DataFrame(enriched_events)
med_outcome_df.head()

,patient,change_from,change_to,effect_from,effect_to,started,stopped,event_visit,dass_depression_delta,dass_fear_delta,dass_stress_delta,midas_delta,vr12_msc_delta,vr12_psc_delta,gvas_delta,pgic_delta,chiq_delta
0,10614987,Patients_V1_02-03-2026,Patients_V3_02-03-2026,Patients_V3_02-03-2026,Patients_V4_02-03-2026,[Magnesium],[],Patients_V3_02-03-2026,-2.0,-1.0,2.0,4.0,-9.365798,-3.456817,-33.0,3.0,NaN
1,10614987,Patients_V7_02-03-2026,Patients_V9_02-03-2026,Patients_V9_02-03-2026,Patients_V10_02-03-2026,[Metoprolol],[],Patients_V9_02-03-2026,0.0,-1.0,1.0,0.0,-2.392092,-2.055618,15.0,0.0,NaN
2,10614987,Patients_V10_02-03-2026,Patients_V11_02-03-2026,Patients_V11_02-03-2026,Patients_Vlast_02-03-2026,[Venlafaxin],[],Patients_V11_02-03-2026,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,NaN
3,10740020,Patients_V1_02-03-2026,Patients_V2_02-03-2026,Patients_V2_02-03-2026,Patients_V3_02-03-2026,[Galcanezumab],[],Patients_V2_02-03-2026,0.0,1.0,1.0,4.0,2.967525,-2.624175,-8.0,4.0,NaN
4,10740020,Patients_V4_02-03-2026,Patients_V5_02-03-2026,Patients_V5_02-03-2026,Patients_V6_02-03-2026,[Eptinezumab],[],Patients_V5_02-03-2026,-3.0,-2.0,-2.0,-3.0,8.999836,6.084490,29.0,-2.0,NaN

In [110]:
import numpy as np

def patient_stats(df, col):
    vals = df[col].dropna().values
    if len(vals) < 3:
        return None, None

    return np.mean(vals), np.std(vals)

In [111]:
def is_patient_outlier(value, mean, std):
    if std is None or std == 0 or np.isnan(std):
        return False
    return abs(value - mean) > 2 * std

In [113]:
scores = [
    "dass_depression_delta",
    "dass_fear_delta",
    "dass_stress_delta",
    "midas_delta",
    "vr12_msc_delta",
    "vr12_psc_delta",
    "gvas_delta",
    "pgic_delta",
    "chiq_delta"
]

events = []

for pid, sub in med_outcome_df.groupby("patient"):

    for score in scores:

        if score not in sub.columns:
            continue

        mean, std = patient_stats(sub, score)

        if mean is None:
            continue

        for row in sub.to_dict("records"):

            val = row[score]

            if val is None or np.isnan(val):
                continue

            if is_patient_outlier(val, mean, std):

                events.append({
                    "patient": pid,
                    "from_visit": row["effect_from"],
                    "to_visit": row["effect_to"],
                    "med_started": row["started"],
                    "med_stopped": row["stopped"],
                    "score": score,
                    "value": val,
                    "mean_patient": mean,
                    "std_patient": std,
                    "z_like": (val - mean) / std if std else None
                })

In [114]:
import pandas as pd

events_df = pd.DataFrame(events)
events_df

,patient,from_visit,to_visit,med_started,med_stopped,score,value,mean_patient,std_patient,z_like
0,21937256,Patients_V3_02-03-2026,Patients_V4_02-03-2026,[Metoprolol],[],dass_stress_delta,-7.000000,-2.000000,2.449490,-2.041241
1,21937256,Patients_V7_02-03-2026,Patients_V8_02-03-2026,[Flunarizin],[],midas_delta,-13.000000,-1.833333,5.273097,-2.117667
2,22242277,Patients_V16_02-03-2026,Patients_V17_02-03-2026,[Erenumab],[],midas_delta,74.000000,-0.833333,36.965825,2.024392
3,28010143,Patients_V6_02-03-2026,Patients_V7_02-03-2026,[Andere Prophylaxe],[],vr12_psc_delta,13.244546,1.809273,5.596778,2.043189
4,28356996,Patients_V12_02-03-2026,Patients_V13_02-03-2026,[Atogepant],[],vr12_psc_delta,10.643677,1.083431,4.471574,2.138005
5,29264108,Patients_V2_02-03-2026,Patients_V3_02-03-2026,[Amitriptylin],[],dass_fear_delta,2.000000,0.333333,0.745356,2.236068
6,29264108,Patients_V11_02-03-2026,Patients_V12_02-03-2026,[Magnesium],[],dass_stress_delta,2.000000,-1.500000,1.707825,2.049390
7,34865046,Patients_V12_02-03-2026,Patients_V13_02-03-2026,[Topiramat],[],dass_depression_delta,-12.000000,1.571429,5.900536,-2.300033
8,34865046,Patients_V5_02-03-2026,Patients_V6_02-03-2026,[Opipramol],[],dass_fear_delta,-5.000000,0.000000,2.267787,-2.204793
9,34865046,Patients_V11_02-03-2026,Patients_V12_02-03-2026,[Flunarizin],[],pgic_delta,3.000000,-0.428571,1.498298,2.288310
10,37802671,Patients_V3_02-03-2026,Patients_V4_02-03-2026,[Magnesium],[],dass_depression_delta,11.000000,0.285714,4.802210,2.231115
11,37802671,Patients_V3_02-03-2026,Patients_V4_02-03-2026,[Magnesium],[],vr12_psc_delta,-17.456036,-1.425488,7.726400,-2.074776
12,82734617,Patients_V5_02-03-2026,Patients_V6_02-03-2026,[Amitriptylin],[],dass_fear_delta,-3.000000,1.142857,1.807016,-2.292651
13,98872856,Patients_V8_02-03-2026,Patients_V10_02-03-2026,[Eptinezumab],[],dass_depression_delta,-4.000000,-1.000000,1.414214,-2.121320